---
title: "Painel de Violência Interpessoal e Autoprovocada"
lang: pt-BR

format:
  dashboard:
    theme: [cosmo, senado.scss]
    logo: assets/logo-datasenado.jpg
    orientation: rows
    scrolling: false
    expandable: true

execute:
  echo: false
  warning: false
  message: false
  cache: true
---

# Sinan

## Subpainéis {.tabset}

```{r Motivos, cache=FALSE}
#| title: Motivos


rm(list = ls())
library(tidyverse)
library(echarts4r)
load('tabelas/dados_001.rda')
source('funcoes_graf.r')
source('config.R')

# teste

uf_ibge <- tibble::tribble(
  ~cod_uf, ~uf, ~nome_uf,
  11, "RO", "Rondônia",
  12, "AC", "Acre",
  13, "AM", "Amazonas",
  14, "RR", "Roraima",
  15, "PA", "Pará",
  16, "AP", "Amapá",
  17, "TO", "Tocantins",
  21, "MA", "Maranhão",
  22, "PI", "Piauí",
  23, "CE", "Ceará",
  24, "RN", "Rio Grande do Norte",
  25, "PB", "Paraíba",
  26, "PE", "Pernambuco",
  27, "AL", "Alagoas",
  28, "SE", "Sergipe",
  29, "BA", "Bahia",
  31, "MG", "Minas Gerais",
  32, "ES", "Espírito Santo",
  33, "RJ", "Rio de Janeiro",
  35, "SP", "São Paulo",
  41, "PR", "Paraná",
  42, "SC", "Santa Catarina",
  43, "RS", "Rio Grande do Sul",
  50, "MS", "Mato Grosso do Sul",
  51, "MT", "Mato Grosso",
  52, "GO", "Goiás",
  53, "DF", "Distrito Federal"
) |> arrange(uf)


dados_001 |> 
  filter(ciclo_vida %in% c("Criança", "Adolescente"),
         ciclo_vida != "Jovem"  ,
         #year(data_notific) >2020
         ) |> 
  group_by(data_notific, ciclo_vida, motivo_violencia) |> 
  summarise(n=sum(n), 
            .groups = 'drop') |> 
  grafico_linhas_facetas(
    eixo_x = data_notific,
    eixo_y = n,
    grupo = ciclo_vida,
    titulo = "Nº notificações",
    escala_y_livre = TRUE,
    facet = motivo_violencia,
    colunas = 3,
   
  )

  
```

```{r Agressores, cache=FALSE}
#| title: Agressores

dados_001 |> 
  filter(ciclo_vida %in% c("Criança", "Adolescente"),
         ciclo_vida != "Jovem"  ,
         #year(data_notific) >2020
         ) |> 
  group_by(data_notific, ciclo_vida, autor) |> 
  summarise(n=sum(n), 
            .groups = 'drop') |> 
  grafico_linhas_facetas(
    eixo_x = data_notific,
    eixo_y = n,
    grupo = ciclo_vida,
    titulo = "Nº notificações",
    escala_y_livre = TRUE,
    facet = autor,
    colunas = 5,
   
  )

  
```



```{r Agressores x Vítimas}
#| title: Agressores e vítimas


library(dplyr)
library(ggplot2)
library(scales)

dados_heatmap <- dados_001 |>
  mutate(
    ciclo_vida       = coalesce(ciclo_vida, "Não informado"),
    ciclo_vida_autor = coalesce(ciclo_vida_autor, "Ignorado")
  ) |>
  group_by(ciclo_vida, ciclo_vida_autor) |>
  summarise(n = sum(n, na.rm = TRUE), .groups = "drop")

g1 <- ggplot(
  dados_heatmap,
  aes(
    x = ciclo_vida_autor,
    y = ciclo_vida,
    fill = n
  )
) +
  geom_tile(color = "white", linewidth = 0.6) +
  geom_text(
    aes(label = label_number(big.mark = ".", decimal.mark = ",")(n)),
    size = 3
  ) +
  scale_fill_viridis_c(
    trans = "log1p",
    labels = label_number(big.mark = ".", decimal.mark = ","),
    name = "Frequência"
  ) +
  labs(
    x = "Ciclo de vida do autor",
    y = "Ciclo de vida",
    title = "Distribuição segundo o ciclo de vida e o ciclo de vida do autor"
  ) +
  coord_equal() +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold")
  )




g2 <- ggplot(
  dados_heatmap |> filter(ciclo_vida %in% c('Adolescente', 'Criança')),
  aes(
    x = ciclo_vida_autor,
    y = ciclo_vida,
    fill = n
  )
) +
  geom_tile(color = "white", linewidth = 0.6) +
  geom_text(
    aes(label = label_number(big.mark = ".", decimal.mark = ",")(n)),
    size = 3
  ) +
  scale_fill_viridis_c(
    trans = "log1p",
    labels = label_number(big.mark = ".", decimal.mark = ","),
    name = "Frequência"
  ) +
  labs(
    x = "Ciclo de vida do autor",
    y = "Ciclo de vida",
    title = "Distribuição criança/adolescente e o ciclo de vida do autor"
  ) +
  coord_equal() +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(face = "bold")
  )


library(patchwork)

g1
g2

```


```{r principais cruzamentos}
#| title: Autor x Vítima x Causa

pacman::p_load(dplyr, gtExtras, gt, scales)



dados_001 |> 
  filter(ciclo_vida %in% c("Criança", "Adolescente"),
         ciclo_vida != "Jovem") |> 
  group_by(ciclo_vida_autor, ciclo_vida, motivo_violencia) |> 
  summarise(n=sum(n), .groups = 'drop') |> 
  arrange(-n) |> 
  head(20) |> 
  mutate(
    ciclo_vida_autor = coalesce(ciclo_vida_autor, "Não informado"),
    ciclo_vida       = coalesce(ciclo_vida, "Não informado"),
    motivo_violencia = coalesce(motivo_violencia, "Não informado"),
    barra             = n
  ) |>
  gt() |>
  cols_label(
    ciclo_vida_autor = "Ciclo de vida do autor",
    ciclo_vida       = "Ciclo de vida da vítima",
    motivo_violencia = "Motivo da violência",
    n                 = "Frequência",
    barra             = "Frequência relativa"
  ) |>
  fmt_number(
    columns = n,
    decimals = 0,
    sep_mark = ".",
    dec_mark = ","
  ) |>
  gt_plt_bar(
    column = barra,
    scaled = TRUE,
    color = "#3B82F6",
    background = "#E5E7EB",
    width = 60
  ) |>
  cols_align(
    align = "left",
    columns = c(
      ciclo_vida_autor,
      ciclo_vida,
      motivo_violencia
    )
  ) |>
  cols_align(
    align = "right",
    columns = n
  ) |>
  cols_width(
    ciclo_vida_autor ~ px(150),
    ciclo_vida       ~ px(150),
    motivo_violencia ~ px(250),
    n                 ~ px(110),
    barra             ~ px(180)
  )


```


```{r principais cruzamentos - gênero}
#| title: Autor x Vítima x Gênero

ordem <- dados_001 |> 
  filter(ciclo_vida %in% c("Criança", "Adolescente")) |> 
  group_by(motivo_violencia) |> 
  summarise(
    n = sum(n, na.rm = TRUE),
    .groups = "drop"
  ) |> 
  arrange(desc(n), motivo_violencia) |> 
  slice_head(n = 10) |> 
  pull(motivo_violencia)

dados_001 |> 
  filter(
    ciclo_vida %in% c("Criança", "Adolescente"),
    match(motivo_violencia, ordem, nomatch = 0L) > 0L
  ) |> 
  group_by(
    genero_autor,
    genero_vitima,
    motivo_violencia
  ) |> 
  summarise(
    n = sum(n, na.rm = TRUE),
    .groups = "drop"
  ) |> 
  mutate(
    ordem_motivo = match(motivo_violencia, ordem)
  ) |>
  arrange(
    ordem_motivo,
    desc(n)
  ) |> 
  mutate(
    genero_vitima = coalesce(
      genero_vitima,
      "Não informado"
    ),
    genero_autor = coalesce(
      genero_autor,
      "Não informado"
    ),
    motivo_violencia = coalesce(
      motivo_violencia,
      "Não informado"
    ),
    barra = n
  ) |>
  select(-ordem_motivo) |>
  gt() |>
  cols_label(
    genero_autor     = "Gênero do autor",
    genero_vitima    = "Gênero da vítima",
    motivo_violencia = "Motivo da violência",
    n                 = "Frequência",
    barra             = "Frequência relativa"
  ) |>
  fmt_number(
    columns = n,
    decimals = 0,
    sep_mark = ".",
    dec_mark = ","
  ) |>
  gt_plt_bar(
    column = barra,
    scaled = TRUE,
    color = "#3B82F6",
    background = "#E5E7EB",
    width = 60
  ) |>
  cols_align(
    align = "left",
    columns = c(
      genero_autor,
      genero_vitima,
      motivo_violencia
    )
  ) |>
  cols_align(
    align = "right",
    columns = n
  ) |>
  cols_width(
    genero_autor     ~ px(150),
    genero_vitima    ~ px(150),
    motivo_violencia ~ px(250),
    n                 ~ px(110),
    barra             ~ px(180)
  )

```


# Justiça - CNJ

## Subpainéis {.tabset}

```{r Nº Processos, cache=FALSE}
#| title: Nº Processos

library(tidyverse)
library(echarts4r)

load('justica/processos_df.rda')

  
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(stringr)

processos_mes <- processos_df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[23],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )
  

  
```


```{r AC}
#| title: AC



estado <- "AC"


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[1],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```





```{r AL}
#| title: AL



estado <- uf_ibge$uf[2]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[2],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```




```{r AM}
#| title: AM



estado <- uf_ibge$uf[3]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[3],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r AP}
#| title: AP



estado <- uf_ibge$uf[4]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[4],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r BA}
#| title: BA



estado <- uf_ibge$uf[5]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[5],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r CE}
#| title: CE



estado <- uf_ibge$uf[6]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[6],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r DF}
#| title: DF
estado <- uf_ibge$uf[7]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[7],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r ES}
#| title: ES

estado <- uf_ibge$uf[8]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[8],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r GO}
#| title: GO



estado <- uf_ibge$uf[9]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[9],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r MA}
#| title: MA



estado <- uf_ibge$uf[10]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[10],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r MG}
#| title: MG



estado <- uf_ibge$uf[11]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[11],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r MS}
#| title: MS



estado <- uf_ibge$uf[12]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[12],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r MT}
#| title: MT



estado <- uf_ibge$uf[13]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[13],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r PA}
#| title: PA



estado <- uf_ibge$uf[14]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[14],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r PB}
#| title: PB



estado <- uf_ibge$uf[15]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[15],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r PE}
#| title: PE



estado <- uf_ibge$uf[16]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[16],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r PI}
#| title: PI



estado <- uf_ibge$uf[17]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[17],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r PR}
#| title: PR



estado <- uf_ibge$uf[18]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[18],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r RJ}
#| title: RJ



estado <- uf_ibge$uf[19]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[19],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r RN}
#| title: RN



estado <- uf_ibge$uf[20]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[20],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r RO}
#| title: RO



estado <- uf_ibge$uf[21]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[21],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r RR}
#| title: RR



estado <- uf_ibge$uf[22]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[22],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r RS}
#| title: RS



estado <- uf_ibge$uf[23]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
    subtitle = uf_ibge$nome_uf[23],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r SC}
#| title: SC



estado <- uf_ibge$uf[24]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[24],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r SE}
#| title: SE



estado <- uf_ibge$uf[25]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[25],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r SP}
#| title: SP



estado <- uf_ibge$uf[26]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[26],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```






```{r TO}
#| title: TO



estado <- uf_ibge$uf[27]


df <- map_dfr(list.files("justica/processos_ano_uf",
                         pattern = paste0("^processos_", estado, ".*\\.rda$"),
                         full.names = TRUE
), function(arq) {env <- new.env()
objetos <- load(arq, envir = env)

objetos |>
  map(\(x) env[[x]]) |>
  keep(is.data.frame) |>
  bind_rows()})  
  




processos_mes <- df |>
  mutate(
    data = ymd(str_sub(data_ajuizamento, 1, 8)),
    mes  = floor_date(data, unit = "month")
  ) |>
  distinct(mes, numero_processo) |>
  count(mes, name = "Processos")

notificacoes_mes <- dados_001 |>
  filter(SG_UF_OCOR == uf_ibge$cod_uf[which(uf_ibge$uf == estado)]) |> 
  mutate(
    data_notific = ymd(data_notific),
    mes = floor_date(data_notific, unit = "month")
  ) |>
  summarise(
    Notificações = sum(n, na.rm = TRUE),
    .by = mes
  )

dados_grafico <- full_join(
  processos_mes,
  notificacoes_mes,
  by = "mes"
) |>
  pivot_longer(
    cols = c(Processos, Notificações),
    names_to = "serie",
    values_to = "n"
  )


ggplot(
  dados_grafico,
  aes(x = mes, y = n, color = serie)
) +
  geom_line(linewidth = 0.9, na.rm = TRUE) +
  scale_color_manual(
    values = c(
      "Processos" = "#0072B2",
      "Notificações" = "#D55E00"
    )
  ) +
  scale_x_date(
    date_breaks = "2 years",
    date_labels = "%Y"
  ) +
  labs(
    title = "Processos ajuizados e notificações",
        subtitle = uf_ibge$nome_uf[27],
    x = NULL,
    y = "Número de registros",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold")
  )


```


```{r graf_barras_assunto}
#| title: Assuntos
rm(list = ls())
library(dplyr)
library(scales)
library(tidyr)
library(stringr)
library(purrr)

ler_rda_df <- function(arquivo) {
  ambiente <- new.env()
  objetos <- load(arquivo, envir = ambiente)
  
  objetos |>
    map(\(nome) ambiente[[nome]]) |>
    keep(is.data.frame) |>
    list_rbind()
}

processos_df <- list.files(
  "justica/processos_ano_uf",
  pattern = "\\.(rda|RData)$",
  full.names = TRUE,
  ignore.case = TRUE
) |>
  map(ler_rda_df) |>
  list_rbind()


assuntos_df <- processos_df |>
  select(numero_processo, assunto_nome) |>
  filter(!is.na(assunto_nome)) |>
  separate_longer_delim(assunto_nome, delim = ";") |>
  mutate(assunto_nome = str_squish(assunto_nome)) |>
  filter(assunto_nome != "") |>
  distinct(numero_processo, assunto_nome) |>
  count(assunto_nome, name = "n", sort = TRUE) |> 
  head(20)


assuntos_df |> 
  mutate(assunto_nome = reorder(assunto_nome, n)) |> 
  ggplot(aes(x = assunto_nome, y = n))+
  geom_col()+
  coord_flip()+
  scale_y_continuous(
    labels = label_number(
      big.mark = ".",
      decimal.mark = ",",
      accuracy = 1
    )
  ) +
  labs(
    title = "Assuntos mais frequentes - ECA",
    x = "Assunto",
    y = "Número de processos"
  )+
  theme_minimal()


```

# Conselhos tutelares

## Subpainéis {.tabset}


```{r coropletico_conselhos_tutelares}
#| title: "Conselhos tutelares: ano base 2023 - fonte: IBGE"

# Dados --------------------------------------------------------------------

load("conselhos_tutelares/cons_tut.rda")

library(geobr)
library(sf)
library(dplyr)
library(ggplot2)


# Malha municipal ----------------------------------------------------------

mun_geo <- read_municipality(
  code_muni = "all",
  year = 2022,
  simplified = TRUE
)



# Junta os dados à malha municipal -----------------------------------------

mapa_ct <- mun_geo |>
  mutate(
    mun = as.character(code_muni)
  ) |>
  left_join(
    cons_tut |>
      mutate(mun = as.character(mun)),
    by = "mun"
  )


# Quintis ------------------------------------------------------------------
#
# 0 é mantido como uma categoria própria.
# Os demais municípios são divididos em quintis.

x <- mapa_ct$ct_por_pop_crianca_adolescente

breaks_ct <- quantile(
  x[
    x > 0 &
      !is.na(x)
  ],
  probs = seq(0, 1, 0.2),
  na.rm = TRUE,
  names = FALSE
)

# Evita problema caso dois quantis sejam exatamente iguais
breaks_ct <- unique(breaks_ct)


# Cria os intervalos apenas para valores positivos

faixa_pos <- cut(
  x,
  breaks = breaks_ct,
  include.lowest = TRUE,
  dig.lab = 3,
  ordered_result = TRUE
)


# Monta a variável final:
# 0 + quintis positivos

mapa_ct <- mapa_ct |>
  mutate(
    faixa_ct = case_when(
      is.na(ct_por_pop_crianca_adolescente) ~ NA_character_,
      ct_por_pop_crianca_adolescente == 0   ~ "0",
      TRUE                                  ~ as.character(faixa_pos)
    ),
    
    faixa_ct = factor(
      faixa_ct,
      levels = c(
        "0",
        levels(faixa_pos)
      )
    )
  )


# Mapa ---------------------------------------------------------------------

ggplot(mapa_ct) +
  geom_sf(
    aes(fill = faixa_ct),
    color = NA
  ) +
  scale_fill_viridis_d(
    option = "C",
    direction = -1,
    na.value = "red",
    name = "Conselhos tutelares\npor 100 mil crianças\ne adolescentes"
  ) +
  labs(
    title = "Conselhos tutelares por população de crianças e adolescentes",
    subtitle = "Número de conselhos tutelares por 100 mil crianças e adolescentes, segundo município — Brasil, 2023",
    caption = "Fonte: IBGE, Pesquisa de Informações Básicas Municipais (MUNIC), 2023 e Censo, 2022."
  ) +
  theme_void() +
  theme(
    plot.title = element_text(
      face = "bold",
      size = 16
    ),
    plot.subtitle = element_text(
      size = 11,
      margin = margin(b = 12)
    ),
    plot.caption = element_text(
      size = 9,
      hjust = 0
    ),
    legend.title = element_text(
      size = 10,
      face = "bold"
    ),
    legend.text = element_text(
      size = 9
    )
  )

```



# DATASUS

## Subpainéis {.tabset}


```{r sihsus_rd}
#| title: "Atentimentos hospitalares"
#| fig-width: 15
#| fig-height: 8
#| out-width: 100%
#| fig-format: svg


load('sih/sih_viol_sexual')

pacman::p_load(tidyverse,
               ggrepel,
               patchwork)

base <- sih_viol_sexual |> 
  transmute(
    cod_mun = MUNIC_RES,
    data = ymd(DT_INTER),
    genero = case_when(
      SEXO == "1" ~ "Masc",
      SEXO == "3" ~ "Fem",
      T ~ "NI",
      ),
    idade = time_length(interval(ymd(NASC), ymd(DT_INTER)), "years") |> floor(),
    ciclo_vida = case_when(                                                     # Referência: ECA
      idade <= 11 ~ "Criança",
      idade <= 17 ~ "Adolescente",
      TRUE ~ "Adulto"
    )
    ) |> 
  mutate(data = floor_date(data, unit = 'quarter')) |> 
  filter(data != max(data)) 

# Graf 1 - Criança -------

dados_graf <- base |> 
  filter(ciclo_vida == "Criança") |> 
  group_by(data) |> 
  summarise(
    n = n(),
    .groups = "drop"
  )

maximo <- dados_graf |> 
  slice_max(n, n = 1, with_ties = FALSE) |> 
  mutate(
    trimestre = paste0(
      year(data),
      " - ",
      quarter(data),
      "º tri."
    )
  )

g1 <- ggplot(dados_graf, aes(x = data, y = n)) +
  geom_line() +
  geom_point(
    data = maximo,
    size = 2
  ) +
  geom_label_repel(
    data = maximo,
    aes(label = paste0(trimestre, "\n", n, " notificações")),
    direction = "y",
    nudge_x = -2500,
    nudge_y = -7,
    size = 3.5
  ) +
  theme_minimal() +
  labs(
    title = paste(
      "Violência sexual",
      "-",
      min(year(base$data)),
      "a",
      max(year(base$data))
    ),
    subtitle = "Criança",
    y = "Notificações",
    x = "Trimestre"
  )

# Graf 2 - Adolescente -------

dados_graf <- base |> 
  filter(ciclo_vida == "Adolescente") |> 
  group_by(data) |> 
  summarise(
    n = n(),
    .groups = "drop"
  )

maximo <- dados_graf |> 
  slice_max(n, n = 1, with_ties = FALSE) |> 
  mutate(
    trimestre = paste0(
      year(data),
      " - ",
      quarter(data),
      "º tri."
    )
  )

g2 <- ggplot(dados_graf, aes(x = data, y = n)) +
  geom_line() +
  geom_point(
    data = maximo,
    size = 2
  ) +
  geom_label_repel(
    data = maximo,
    aes(label = paste0(trimestre, "\n", n, " notificações")),
    direction = "y",
    nudge_x = -2500,
    nudge_y = -7,
    size = 3.5
  ) +
  theme_minimal() +
  labs(
    title = paste(
      "Violência sexual",
      "-",
      min(year(base$data)),
      "a",
      max(year(base$data))
    ),
    subtitle = "Adolescente",
    y = "Notificações",
    x = "Trimestre"
  )


g3 <- base |> 
  filter(ciclo_vida == "Criança") |> 
  group_by(genero, idade) |> 
  summarise(n=n(), .groups = 'drop') |> 
  ggplot(aes(x = idade, y = n, color = genero))+
  geom_line()+
  theme_minimal()+
  labs(
    title = paste(
      "Violência sexual",
      "-",
      min(year(base$data)),
      "a",
      max(year(base$data))
    ),
    subtitle = "Criança",
    y = "Notificações",
    x = "Trimestre"
  )


g4 <- base |> 
  filter(ciclo_vida == "Adolescente") |> 
  group_by(genero, idade) |> 
  summarise(n=n(), .groups = 'drop') |> 
  ggplot(aes(x = idade, y = n, color = genero))+
  geom_line()+
  theme_minimal()+
  labs(
    title = paste(
      "Violência sexual",
      "-",
      min(year(base$data)),
      "a",
      max(year(base$data))
    ),
    subtitle = "Adolescente",
    y = "Notificações",
    x = "Trimestre"
  )

fmt_tri <- function(x) {
  paste0(quarter(x), "º trim ", year(x))
}

base_4tri <- base |>
  filter(dense_rank(desc(data)) <= 4)

g5 <- base_4tri |> 
  filter(ciclo_vida == "Criança") |> 
  group_by(genero, idade) |> 
  summarise(
    n = n(),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = idade, y = n, color = genero)) +
  geom_line() +
  theme_minimal() +
  labs(
    title = paste(
      "Violência sexual -",
      fmt_tri(min(base_4tri$data, na.rm = TRUE)),
      "a",
      fmt_tri(max(base_4tri$data, na.rm = TRUE))
    ),
    subtitle = "Criança",
    y = "Notificações",
    x = "Idade"
  )


fmt_tri <- function(x) {
  paste0(quarter(x), "º trim ", year(x))
}

base_4tri <- base |>
  filter(dense_rank(desc(data)) <= 4)

g6 <- base_4tri |> 
  filter(ciclo_vida == "Adolescente") |> 
  group_by(genero, idade) |> 
  summarise(
    n = n(),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = idade, y = n, color = genero)) +
  geom_line() +
  theme_minimal() +
  labs(
    title = paste(
      "Violência sexual -",
      fmt_tri(min(base_4tri$data, na.rm = TRUE)),
      "a",
      fmt_tri(max(base_4tri$data, na.rm = TRUE))
    ),
    subtitle = "Adolescente",
    y = "Notificações",
    x = "Idade"
  )


(g1 + g2 + g3 + g4 + g5 + g6) +
  plot_layout(
    ncol = 2,
    nrow = 3,
    guides = "collect"
  ) &
  theme(
    legend.position = "bottom",
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    axis.title = element_text(size = 9),
    axis.text = element_text(size = 8)
  )


```

